INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('1','Neznámá soutěž',45,5);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('all','all',45,5);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A1A','11 PRAŽSKÁ TEPLÁRENSKÁ PŘEBOR MUŽŮ	&Muži Krajský přebor skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110Č1A','27 - 1. LIGA GENTLEMANŮ 40+ PODZIM &Hráči 40+ Krajský přebor skupina A',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A2A','12 M-1.A/A	&Muži 1. A třída skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A2B','13 M-1.A/B	&Muži 1. A třída skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A3A','14 M-1.B/A	&Muži 1. B třída skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A3B','15 M-1.B/B	&Muži 1. B třída skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A4A','21 M-2/A	&Neurčeno Hl. město Praha skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A4B','22 M-2/B	&Neurčeno Hl. město Praha skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A4C','23 M-2/C	&Neurčeno Hl. město Praha skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A5A','24 M-3/A	&Neurčeno Hl. město Praha skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A5B','25 M-3/B	&Neurčeno Hl. město Praha skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110A5C','26 M-3/C	&Neurčeno Hl. město Praha skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110Č1A','27 - 1. LIGA GENTLEMANŮ 40+ PODZIM &Hráči 40+ Krajský přebor skupina A',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110Č1B','28 - 2.LIGA GENTLEMANŮ 40+ PODZIM &Hráči 40+ Krajský přebor skupina B',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110Č1C','29 - 3. LIGA GENTLEMANŮ 40+ PODZIM &Hráči 40+ Krajský přebor skupina C',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110C1A','31 PŘEBOR STARŠÍHO DOROSTU &Dorost - starší Krajský přebor skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110C2A','32 D-1/A &Dorost - starší 1. A třída skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110C3A','33 D-1/B &Dorost - starší 1. B třída skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110D1A','41 PŘEBOR MLADŠÍHO DOROSTU &Dorost - mladší Krajský přebor skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110D2A','42 MD-1/A &Dorost - mladší 1. A třída skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110D4A','43 MD-2/A &Neurčeno Hl. město Praha skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110D4C','45 MD-2C &Neurčeno Hl. město Praha skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110D4B','44 MD-2B &Neurčeno Hl. město Praha skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110E1A','51 PŘEBOR STARŠÍCH ŽÁKŮ	&Žáci - starší Krajský přebor skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110E2A','52 SŽ-1.A/A &Žáci - starší 1. A třída skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110E2B','53 SŽ-1.A/B	&Žáci - starší 1. A třída skupina B',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110E3A','54 SŽ-2/A &Žáci - starší 1. B třída skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110E3B','55 SŽ-2/B &Žáci - starší 1. B třída skupina B',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110E3C','56 SŽ-2/C &Žáci - starší 1. B třída skupina C',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F1A','61 PŘEBOR MLADŠÍCH ŽÁKŮ &Žáci - mladší Krajský přebor skupina A',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F2A','62 MŽ-1/A &Žáci - mladší 1. A třída skupina A',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F2B','63 MŽ-1/B &Žáci - mladší 1. A třída skupina B',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F3A','64 MŽ-2/A &Žáci - mladší 1. B třída skupina A',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F3B','65 MŽ-2/B &Žáci - mladší 1. B třída skupina B',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F3C','66 MŽ-2/C &Žáci - mladší 1. B třída skupina C',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F3D','67 MŽ-2/D &Žáci - mladší 1. B třída skupina D',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F4A','68 MŽ-3/A &Neurčeno Hl. město Praha skupina A',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F4B','69 MŽ-3/B &Neurčeno Hl. město Praha skupina B',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110F4C','70 MŽ-3/C &Neurčeno Hl. město Praha skupina C',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3A','G3A 2013 (2HP) - J. NOVOTNÉHO &Přípravka - starší 1. B třída skupina A',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3B','G3B 2014 (2HP) - J. NOVOTNÉHO &Přípravka - starší 1. B třída skupina B',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3C','G3C 2013 (2HP) - ŠMICROVA &Přípravka - starší 1. B třída skupina C',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3D','G3D 2014 (2HP) - ŠMICROVA &Přípravka - starší 1. B třída skupina D',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3E','G3E 2013 (2HP) - J. NOVOTNÉHO II. &Přípravka - starší 1. B třída skupina E',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3F','G3F 2014 (2HP) - J. NOVOTNÉHO II. &Přípravka - starší 1. B třída skupina F',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3G','G3G 2013/14 (2HP) &Přípravka - starší 1. B třída skupina G',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3H','G3H 2013/14 (2HP) &Přípravka - starší 1. B třída skupina H',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3I','G3I 2013/14 (2HP) &Přípravka - starší 1. B třída skupina I',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3J','G3J 2013/14 (1HP) &Přípravka - starší 1. B třída skupina J',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3K','G3K 2013/14 (1HP) &Přípravka - starší 1. B třída skupina K',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3L','G3L 2013/14 (1HP) &Přípravka - starší 1. B třída skupina L',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3M','G3M 2013/14 (1HP) &Přípravka - starší 1. B třída skupina M',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3N','G3N 2013/14 (1HP) &Přípravka - starší 1. B třída skupina N',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110G3O','G3P 2013/14 (1HP) &Přípravka - starší 1. B třída skupina O',34,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3A','H3A 2015 (2HP) - J. NOVOTNÉHO &Přípravka - mladší 1. B třída skupina A',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3B','H3B 2016 (2HP) - J. NOVOTNÉHO &Přípravka - mladší 1. B třída skupina B',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3C','H3C 2015 (2HP) - ŠMICROVA &Přípravka - mladší 1. B třída skupina C',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3D','H3D 2016 (2HP) - ŠMICROVA &Přípravka - mladší 1. B třída skupina D',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3E','H3E 2015 (2HP) - J. NOVOTNÉHO II. &Přípravka - mladší 1. B třída skupina E',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3F','H3F 2016 (2HP) - J. NOVOTNÉHO II. &Přípravka - mladší 1. B třída skupina F',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3G','H3G 2015/16 (2HP) &Přípravka - mladší 1. B třída skupina G',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3H','H3H 2015/16 (2HP) &Přípravka - mladší 1. B třída skupina H',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3I','H3I 2015/16 (1HP) &Přípravka - mladší 1. B třída skupina I',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3J','H3J 2015/16 (1HP) &Přípravka - mladší 1. B třída skupina J',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3K','H3K 2015/16 (1HP) &Přípravka - mladší 1. B třída skupina K',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3L','H3L 2015/16 (1HP) &Přípravka - mladší 1. B třída skupina L',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3M','H3M 2015/16 (1HP) &Přípravka - mladší 1. B třída skupina M',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110H3N','H3N 2015/16 (1HP) &Přípravka - mladší 1. B třída skupina N',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110Z1A','TESKAHOR POHÁR PRAHY - MUŽI(1.KOLO) &Volné Krajský přebor skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110Z2A','POHÁR DOROST (1.KOLO) &Volné 1. A třída skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023110Z3A','POHÁR ŽÁCI (1.KOLO) &Volné 1. B třída skupina A',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002C2A','ČLD U 19&Dorost - starší Divize skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002D2A','ČLD U 17&Dorost - mladší Divize skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E1A','ČLŽ U 15&Neurčeno Řídící komise pro Čechy skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E2A','ČLŽ U 14&Žáci - starší Divize skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F1A','ČLŽ U 13&Neurčeno Řídící komise pro Čechy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F2A','ČLŽ U 12&Žáci - mladší Divize skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002C3A','ČDD U 19 A &Neurčeno Řídící komise pro Čechy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002D3A','ČDD U 17 A &Neurčeno Řídící komise pro Čechy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002C3B','ČDD U 19 B &Neurčeno Řídící komise pro Čechy skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002D3B','ČDD U 17 B &Neurčeno Řídící komise pro Čechy skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002C3C','ČDD U 19 C &Neurčeno Řídící komise pro Čechy skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002D3C','ČDD U 17 C &Neurčeno Řídící komise pro Čechy skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E3A','ČDŽ U 15 A &Neurčeno Řídící komise pro Čechy skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E4A','ČDŽ U 14 A &Neurčeno Řídící komise pro Čechy skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E3B','ČDŽ U 15 B &Neurčeno Řídící komise pro Čechy skupina B',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E4B','ČDŽ U 14 B &Neurčeno Řídící komise pro Čechy skupina B',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E3C','ČDŽ U 15 C &Neurčeno Řídící komise pro Čechy skupina C',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002E4C','ČDŽ U 14 C &Neurčeno Řídící komise pro Čechy skupina C',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F3A','ČDŽ U 13 A &Neurčeno Řídící komise pro Čechy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F4A','ČDŽ U 12 A &Neurčeno Řídící komise pro Čechy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F3B','ČDŽ U 13 B &Neurčeno Řídící komise pro Čechy skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F4B','ČDŽ U 12 B &Neurčeno Řídící komise pro Čechy skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F3C','ČDŽ U 13 C &Neurčeno Řídící komise pro Čechy skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023002F4C','ČDŽ U 12 C &Neurčeno Řídící komise pro Čechy skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005J2A','2.liga žen &Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005J3A','Česká fotbalová liga žen&Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005J4A','Divize A ženy Čechy&Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005J4B','Divize B ženy Čechy&Neurčeno FAČR Ženy skupina B',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005J4C','Divize C ženy Čechy&Neurčeno FAČR Ženy skupina C',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005L1A','1.liga dorostenek&Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005L2A','2.liga dorostenky Čechy&Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005N1A','1.liga starších žákyň Čechy&Neurčeno FAČR Ženy skupina A',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005N2A','1.liga mladších žákyň Čechy&Neurčeno FAČR Ženy skupina A',35,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005N1D','2.liga starších žákyň Čechy 7+1&Neurčeno FAČR Ženy skupina D',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005N1C','2.liga starších žákyň Čechy&Neurčeno FAČR Ženy skupina D',40,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005N2C','2.liga mladších žákyň Čechy&Neurčeno FAČR Ženy skupina D',30,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005Z1A','Pohár žen FAČR 1.předkolo&Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005Z2A','Pohár žen FAČR 1.kolo&Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005K1A','Pohár dorostenek 1.předkolo&Neurčeno FAČR Ženy skupina A',45,0);
INSERT INTO "Competitions" (competition_id, competition_name,match_length,league) VALUES ('2023005K2A','Pohár dorostenek 1.kolo&Neurčeno FAČR Ženy skupina A',45,0);
